<?php

namespace Ailixter\Gears\Example;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Error\Notice;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-10-23 at 13:50:08.
 */
class TestStrictPropsDerivedTest extends TestCase
{

    /**
     * @var TestStrictPropsDerived
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestStrictPropsDerived;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testNotInKeys()
    {
        self::assertNotContains('notdata', $this->object->propertyKeys());
    }

    /**
     * @expectedException PHPUnit\Framework\Error\Notice
     */
    public function testPrivateGet()
    {
        self::assertEmpty($this->object->notdata);
    }

    /**
     * @expectedException \PHPUnit\Framework\Error\Notice
     */
    public function testPrivateSet()
    {
        $this->object->notdata = 123;
        self::assertEmpty($this->object->notdata);
    }

    /**
     */
    public function testGet()
    {
        self::assertNotEmpty($this->object->myPri);
    }

    /**
     */
    public function testSet()
    {
        $this->object->myPri = 123;
        self::assertNotEmpty($this->object->myPri);
    }
}
