<?php

namespace Ailixter\Gears\Example;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-10-21 at 16:41:24.
 */
class TestBoundPropsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var TestBoundProps
     */
    protected $object, $priBinding;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestBoundProps;
//        $this->object->myBoundPro = new TestPropsBinding($this->history);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     */
    public function testUnbound()
    {
        $this->object->myPro = 'string';
        self::assertSame('string', $this->object->myPro);
    }

    /**
     */
    public function testPri1()
    {
        $history = [];
        $binding = new TestPropsBinding('my private', function ($param) use (&$history) {
            $history[] = $param;
        });
        $this->object->myBoundPri = $binding;
        self::assertSame($binding->formatValue($this->object, 'myBoundPri'), $this->object->myBoundPri);
        return [$this->object, $binding, &$history];
    }

    /**
     * @depends testPri1
     */
    public function testPri2(array $arg)
    {
        $object = $arg[0];
        $binding = $arg[1];
        $history =& $arg[2];
        $object->myBoundPri = 123;
        self::assertSame($binding->formatValue($object, 'myBoundPri'), $object->myBoundPri);
        return $history;
    }

    /**
     * @depends testPri2
     */
    public function testPri3(array $history)
    {
        self::assertNotSame([], $history);
    }

    public function testPro()
    {
        $history = [];
        $binding = new TestPropsBinding('my protected', function ($param) use (&$history) {
            $history[] = $param;
        });
        $this->object->myBoundPro = $binding;
        self::assertSame($binding->formatValue($this->object, 'myBoundPro'), $this->object->myBoundPro);
        $this->object->myBoundPro = 123;
        self::assertSame($binding->formatValue($this->object, 'myBoundPro'), $this->object->myBoundPro);
        self::assertNotSame([], $history);
    }

    public function testUndefined()
    {
        $x = $this->object->x;
    }
}
