<?php

namespace Ailixter\Gears\Example;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-10-23 at 22:33:20.
 */
class TestAutoGetSetProps2Test extends \PHPUnit_Framework_TestCase
{

    /**
     * @var TestAutoGetSetProps2
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestAutoGetSetProps2;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testExisting()
    {
        self::assertEquals('x', $this->object->setX('x')->x);
    }

    public function testUnexistingPropDefault()
    {
        self::assertSame('???', $this->object->y);
    }
    public function testGetUnexistingDefault()
    {
        self::assertSame('empty', $this->object->getY('empty'));
    }
    public function testSetUnexisting()
    {
        self::assertSame(1.0, $this->object->setY(1.0)->y);
    }

}
