<?php

namespace Ailixter\Gears\Example;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Error\Error;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-10-17 at 21:18:23.
 */
class TestAutoGetSetPropsTest extends TestCase
{

    /**
     * @var TestAutoGetSetProps
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestAutoGetSetProps;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     */
    public function testSet()
    {
        self::assertInstanceOf(get_class($this->object), $this->object->setX('x'));
        return $this->object;
    }

    /**
     * @depends testSet
     */
    public function testGet(TestAutoGetSetProps $test)
    {
        self::assertEquals('x', $test->getX());
    }

}
